variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"  # Force git to clone submodules with HTTPS 

stages:
  - prepare
  - lint
#   - test

prepare:
  image: $TIQI_PODMAN_IMAGES_URL/python:3.10
  tags:
    - podman-nosid # ISG managed machine, subuid and subgid entries not configured
  stage: prepare
  script:
    - poetry install

# test:
#   stage: test
#   script:
#     - poetry run pytest -v


lint_autopep8:
  stage: lint
  script:
    - |
      CHANGES=$(poetry run autopep8 --diff --recursive .)
      if [ -n "$CHANGES" ]; then
        echo "autopep8 found the following changes:"
        echo "$CHANGES"
        exit 1
      fi


lint_flake8:
  stage: lint
  script:
    - |
      VIOLATIONS=$(flake8)
      if [ -n "$VIOLATIONS" ]; then
        echo "flake8 found the following style violations:"
        echo "$VIOLATIONS"
        exit 1
      fi


