variables:
  GIT_STRATEGY: clone
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true" # Force git to clone submodules with HTTPS

lint_autopep8:
  image: $TIQI_PODMAN_IMAGES_URL/python:3.10
  tags:
    - podman
  script:
    - poetry install
    - poetry run autopep8 --diff --recursive --exclude _*.py --exit-code atomphys/

lint_flake8:
  image: $TIQI_PODMAN_IMAGES_URL/python:3.10
  tags:
    - podman
  script:
    - poetry install
    - poetry run flake8 --config setup.cfg atomphys/

test:
  image: $TIQI_PODMAN_IMAGES_URL/python:3.10
  tags:
    - podman
  script:
    - poetry install
    - poetry run pytest tests/
