stages:
  - prepare
  - lint
#   - test

cache:
  key: python-venv
  paths:
    - .venv

prepare:
  stage: prepare
  script:
    - poetry install

# test:
#   stage: test
#   script:
#     - poetry run pytest -v


lint_autopep8:
  stage: lint
  script:
    - |
      CHANGES=$(poetry run autopep8 --diff --recursive .)
      if [ -n "$CHANGES" ]; then
        echo "autopep8 found the following changes:"
        echo "$CHANGES"
        exit 1
      fi


lint_flake8:
  stage: lint
  script:
    - |
      VIOLATIONS=$(flake8)
      if [ -n "$VIOLATIONS" ]; then
        echo "flake8 found the following style violations:"
        echo "$VIOLATIONS"
        exit 1
      fi


