name: Run Notebook Validation
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install atomphys
        run: pip install .
      - name: Install pytest
        run: pip install pytest nbval
      - name: Install testing dependencies
        run: pip install numpy matplotlib
      - name: Test
        run: pytest -c /dev/null --nbval docs/
