name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install atomphys
        run: pip install .
      - name: Install pytest
        run: pip install pytest pytest-cov
      - name: Test
        run: pytest
      - name: Upload coverage
        uses: codecov/codecov-action@v1
